Repository silverstripe/silverstripe-asset-admin, pull requests merged in 2020-10, with the labels that each got.

#1141 MNT - Quote yaml strings
  behat.yml
Labels: affects/v4, change/minor, effort/easy, impact/medium, type/bug

#1145 FIX Button alignment tweaks
  client/dist/js/bundle.js
  client/dist/styles/bundle.css
  client/src/components/GalleryToolbar/GalleryToolbar.js
  client/src/containers/AssetAdmin/AssetAdmin.scss
  client/src/containers/Gallery/Gallery.scss
  tests/behat/features/change-sort-order.feature
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/UX, type/enhancement

#1111 Switch to using toast instead of form alerts
  client/dist/js/TinyMCE_sslink-file.js
  client/dist/js/bundle.js
  client/lang/src/en.json
  client/src/containers/AssetAdmin/AssetAdmin.js
  client/src/containers/AssetAdmin/tests/AssetAdmin-test.js
  client/src/containers/Gallery/Gallery.js
  client/src/containers/Gallery/tests/Gallery-test.js
  client/src/containers/MoveModal/MoveModal.js
  composer.json
  package.json
  tests/behat/features/manage-file-permissions.feature
  tests/behat/features/manage-files.feature
  yarn.lock
Labels: affects/v4, change/minor, effort/medium, impact/medium, type/enhancement
